#### Exclude
exclude: [".rvmrc", ".rbenv-version", "README.md", "README_en.md", "Rakefile", "changelog.md"]

#### Code Highlighter
# 'pygments' is unsupported on GitHub Pages now.
highlighter: rouge

#### Permalink
# For more see: http://jekyllrb.com/docs/permalinks/
# permalink: pretty
permalink: /:categories/:year/:month/:day/:title/


#### Markdown Processors
# 'redcarpet' is unsupported on GitHub Pages now.
markdown: kramdown
kramdown:
    input: GFM

#### Default Attributes
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

#### Pagination
paginate: 20

#### Site
# title : 김동욱의 기술 블로그
# tagline: 개발자로서 성장하기 위한 나만의 기술 블로그
assets: /assets
# url: https://fkrhtmq123.github.io
# baseurl: https://fkrhtmq123.github.io
url:
baseurl: 

plugins:
  - jekyll-polyglot

#### Language
# language: en    ## blog site languages: en, de
languages: ["ko", "jp"]
default_lang: "ko"
exclude_from_localization: ['javascript', 'images', 'css', 'sitemap.xml']
parallel_localizaion: false

#### Menu
menu:
  Home: /
  Archives: /archives
  About: /about
## you can create `tags` and `categories` folders (I had created them already).
## And create a `index.md` file in each of them.
## set `front-matter`as
## layout: tags (or categories)
## title: tags (or categories)
## ---

#### Widgets
widgets:
- category
- tag
# - tagcloud
- github-visitant
- language
# - links
# - github-card
- rss
## provide seven widgets:github-card,category,tag,rss,archive,tagcloud,links,weibo,douban


#### RSS
rss: /atom.xml ## RSS address.

#### Image
imglogo:
  enable: true             ## display image logo true/false.
  src: img/logo.png        ## `.svg` and `.png` are recommended,please put image into the theme folder `/jacman/source/img`.
favicon: img/favicon.ico   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/jacman/source/img`.
apple_icon: img/jacman.jpg ## size:114px*114px,please put image into the theme folder `/jacman/source/img`.
author_img: img/author.jpg ## size:220px*220px.display author avatar picture.if don't want to display,please don't set this.
banner_img: #img/banner.jpg ## size:1920px*200px+. Banner Picture

#### index post is expanding or not
index:
  expand: true           ## default is unexpanding,so you can only see the short description of each post.
  excerpt_link: Read More

close_aside: false  #close sidebar in post page if true
mathjax: true      #enable mathjax if true
share_to: true #enable share-to buttons if true

#### Author information
author:
  name: Kim Dongwook      ## e.g. wuchong Author name
  intro_line1:  ""    ## your introduction on the bottom of the page
  intro_line2:  ""  ## the 2nd line
  email:      ## e.g. imjark@gmail.com
  twitter:    ## e.g. jarkwu for https://twitter.com/jarkwu
  github:     fkrhtmq123  ## e.g. wuchong for https://github.com/wuchong
  facebook:   ## e.g. imjark for https://facebook.com/imjark
  linkedin:   ## e.g. wuchong1014 for https://www.linkedin.com/in/wuchong1014
  google_plus:    ## e.g. "111190881341800841449" for https://plus.google.com/u/0/111190881341800841449, the "" is needed!
  stackoverflow:  ## e.g. 3222790 for http://stackoverflow.com/users/3222790/jark
## if you set them, the corresponding  share button will show on the footer

#### Toc
toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.
## you can set both of the value to true of neither of them.
## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.

#### Links
# links:
#   码农圈: https://coderq.com
#   Jark's Blog: http://wuchong.me

#### Comment
duoshuo_shortname:    ## e.g. wuchong      your duoshuo short name.       website: http://duoshuo.com
disqus_shortname:     ## e.g. wuchong      your disqus short name.        website: http://disqus.com
hypercomments_id:     ## e.g. 91510        your hypercomments widget id.  website: http://hypercomments.com
yungentie_productkey: ## your netease yungentie product key.              website: https://gentie.163.com
## set only one of them
## duoshuo will be shutting down on June 1, 2017

#### Share button
jiathis:
  enable: false ## if you use jiathis as your share tool,the built-in share tool won't be display.
  id:    ## e.g. 1889330 your jiathis ID.
  tsina: ## e.g. 2176287895 Your weibo id,It will be used in share button.

#### Analytics
google_analytics:
  enable: true
  id: G-GS1WXGS1PB       ## e.g. UA-46321946-2 your google analytics ID.
  site:      ## e.g. wuchong.me your google analytics site or set the value as auto.
## You MUST upgrade to Universal Analytics first!
## https://developers.google.com/analytics/devguides/collection/upgrade/?hl=zh_CN

#### Miscellaneous
fancybox: true        ## if you use gallery post or want use fancybox please set the value to true.
totop: true           ## if you want to scroll to top in every post set the value to true

#### Custom Search
google_cse:
  enable: false
  cx: 018294693190868310296:abnhpuysycw  ## e.g. 018294693190868310296:abnhpuysycw your Custom Search ID.
## https://www.google.com/cse/
## To enable the custom search You must create a "search" folder in '/source' and a "index.md" file
## set the 'front-matter' as
## layout: search
## title: search
## ---

simple_jekyll_search:
  enable: true
  fulltext: false

gems:
 - jemoji
