source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins
#gem 'jekyll-admin', group: :jekyll_plugins

gem "webrick", "~> 1.8.2"
gem 'jekyll', '3.10.0'

gem 'jekyll-polyglot'

gem 'wdm', '>= 0.1.0'